<?php

class Natali_Page_Settings extends Natali_Abstract_Page
{

    public function render($params = [])
    {
        $this->disable = false;

        $url_rest_api_keys = get_site_url() . '/wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys';
        $dbSettings = new Natali_Model_Settings();
        $settings = $dbSettings->getAll();

        $params = [
            'page_title' => __('Настройки', 'wp-natali'),
            'template'  => 'pages/settings',
            'content'   => ['settings' => $settings],
            'settings'  => $settings,
            'disable'   => $this->disable,
        ];

        $params['page'] = str_replace('/', '', esc_attr($_GET['page']));

        if (!WOOCOMMERCE_STATUS) {
            $this->disable = true;

            $params['notices'][] =
                [
                    'content' => 'Пожалуйста активируйте Woocommerce',
                    'type'    => 'error',
                ];

            $params['disable'] = $this->disable;
        }

        if (!$settings['user_key'] || !$settings['secret_key']) {
            $params['notices'] = [
                [
                    'content' => __(sprintf(
                        'Получить <a href="%1s" target="_blank">Api ключи</a> для работы плагина',
                        $url_rest_api_keys
                    ), 'wp-natali'),
                    'type'    => 'warning',
                ],
            ];
        }

        parent::render($params); // TODO: Change the autogenerated stub
    }

    public static function saveSettings()
    {
        $result = [];
        foreach ($_POST as $key => $item) {
            $result[$key] = sanitize_text_field($item);
        }

        unset($result['action']);

        $dbSettings = new Natali_Model_Settings();
        $dbSettings->save($result);

        $response = Natali_Handler::success(__('Настройки:', 'wp-natali'), __('Успешно сохранены', 'wp-natali'));

        $productList = new Natali_Model_ImportTemp();
        $productList->reset();

        echo json_encode($response);

        wp_die();
    }
}
